# Задание 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [7]:
import numpy as np

C = np.reshape(np.arange(0, 16), (4, 4))
A = np.reshape(np.arange(0, 12), (4, 3))
B = np.dot(A, A.T)
D = np.add(B, 10 * C)
D_inv = np.linalg.inv(D)
print(f'Определитель D: {np.linalg.det(D)}')
print()
print(f'Ранг D: {np.linalg.matrix_rank(D)}')
print()
print(f'Обратная матрица D: \n {D_inv}')

Определитель D: 5.18953807259442e-26

Ранг D: 2

Обратная матрица D: 
 [[ 4.66062690e+13 -1.49229688e+13 -1.09972869e+14  7.82895692e+13]
 [ 1.63480451e+14 -3.81454387e+14  2.72467419e+14 -5.44934838e+13]
 [-4.66779710e+14  8.07677680e+14 -2.15016230e+14 -1.25881740e+14]
 [ 2.56692989e+14 -4.11300324e+14  5.25216801e+13  1.02085655e+14]]
