# Задание 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [7]:
import numpy as np

C = np.reshape(np.arange(0, 16), (4, 4))
A = np.reshape(np.arange(0, 12), (4, 3))
B = np.dot(A, A.T)
D = np.add(B, 10 * C)
D_inv = np.linalg.inv(D)
for i in range(4):
    for j in range(4):
        if D_inv[i][j] < 0:
            D_inv[i][j] = 0
        if D_inv[i][j] > 0:
            D_inv[i][j] = 1
print(D_inv)
print()
E = np.where(D_inv, B, C)
print(E)

[[1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 1.]]

[[  5   1   2  32]
 [ 14   5  86   7]
 [  8  86  10  11]
 [ 32  13 212 302]]
