# Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [3]:
import numpy as np

array = np.random.rand(3,4)
print(array.size)
print(array)
print()
new_array = np.reshape(array, (1, -1))
print(new_array.size)
print(new_array)

12
[[0.99428317 0.41287948 0.10214628 0.65029584]
 [0.24010844 0.08478541 0.34968452 0.33241064]
 [0.42873653 0.50139959 0.58763493 0.75217113]]

12
[[0.99428317 0.41287948 0.10214628 0.65029584 0.24010844 0.08478541
  0.34968452 0.33241064 0.42873653 0.50139959 0.58763493 0.75217113]]
