# Задание 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [35]:
import numpy as np

a = np.arange(12,24)
array_1 = np.reshape(a, (2, 6))
print(array_1)
print()
array_2 = np.reshape(a[:10], (2, 5))
print(array_2)
print()
array_3 = np.reshape(a[3:9], (2, 3))
print(array_3)
print()
array_4 = np.reshape(a[8:], (2, 2))
print(array_4)
print()
array_5 = np.reshape(a[3:11], (2, 4))
print(array_5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15 16]
 [17 18 19 20 21]]

[[15 16 17]
 [18 19 20]]

[[20 21]
 [22 23]]

[[15 16 17 18]
 [19 20 21 22]]
