# Задание 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [11]:
import numpy as np

a = np.arange(0, 12)
A = np.reshape(a, (4, 3))
At = A.T
B = np.dot(A, At)
print(B.shape)
print()
print(B)
print()
print(np.linalg.det(B))
print('Обратной матрицы у В не существует, потому что определитель В равен нулю!')

(4, 4)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

0.0
Обратной матрицы у В не существует, потому что определитель В равен нулю!
